# Site settings
title: iLab America Latina
email: ilablatam@instedd.org
description: InSTEDD iLab America Latina website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://http://www.ilabamericalatina.org/" # the base hostname & protocol for your site
twitter_username: instedd
github_username:  instedd

# Build settings
markdown: kramdown
